services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - ":2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest  
      - ":9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,
    depends_on:
      - zookeeper

  minio:
    image: minio/minio:latest
    container_name: minio_log
    command: server /data --console-address ":9001"
    ports:
      - ":9443"
      - "7000:9000"
      - "7001:9001"
    environment:
      MINIO_ACCESS_KEY: Q3AM3UQ867SPQQA43P2F
      MINIO_SECRET_KEY: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
      MINIO_ROOT_USER: Q3AM3UQ867SPQQA43P2F
      MINIO_ROOT_PASSWORD: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    volumes:
      - minio-data:/data
    restart: unless-stopped

  app:
    build: .
    ports:
      - ":8087"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
      - minio

volumes:
  minio-data:
